openapi: 3.0.0
info:
  title: Friend App API
  version: '1.0.0'
  description: |
    Friend App is a sample API for studying simple requests.
  contact:
    email: nikposeda@yandex.ru
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8000

components:
  schemas:
    FriendRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        from_user_id:
          type: integer
          format: int32
        to_user_id:
          type: integer
          format: int32
        accepted:
          type: bool
      required:
        - from_user_id
        - to_user_id

  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - jwt: []

paths:
  /api/v1/friendships/:
    get:
      summary: Отображает список запросов дружбы.
      operationId: listFriendRequests
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FriendRequest'
    post:
      summary: Отправляет запрос на дружбу.
      operationId: sendFriendRequest
      tags:
      - Друг
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendRequest'
      responses:
        '201':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequest'
  /api/v1/friendships/{id}/:
    put:
      summary: Принимает запрос на дружбу.
      operationId: acceptFriendRequest
      tags:
      - Друг
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_accepted:
                  type: boolean
        responses:
          '200':
            description: Успешный ответ
    delete:
      summary: Удаляет запрос на дружбу.
      operationId: deleteFriendRequest
      tags:
      - Друг
      responses:
        '204':
          description: Успешный ответ
